version: "3.8"

services:
  postgesql:
    image: 'postgres:14.1-alpine'
    container_name: tonton_postgesql
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tonton
    volumes:
      - postgres_data:/data/postgres

volumes:
  postgres_data:
